<a href="https://colab.research.google.com/github/josecamilo21/An-lisis-Exploratorio-de-Datos/blob/main/Tarea_Limpieza_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google. colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os
os.chdir('/content/drive/MyDrive/ciencia_de_datos1')

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
os.listdir()

['ratings.csv',
 'cta_calendar.csv',
 'datos_crudos.csv',
 'movies.csv',
 'datos_crudos_tarea.csv',
 'cta_ridership.csv',
 'taxi_vehicles.csv',
 'Chicago_census.csv',
 'Chicago_wards.csv',
 'taxi_owners.csv',
 'S&P500.csv',
 'policies.parquet',
 'Untitled0.ipynb',
 'WorldBank_GDP.csv',
 'land_use.csv',
 'actors_movies.csv',
 'zip_demo.csv',
 'stations.p',
 'financials.csv',
 'billboard.csv',
 'netflix_data.csv',
 'business_owners.csv',
 'police.csv',
 'casts.p',
 'taglines.p',
 'biometria.csv',
 'licenses.csv',
 'movie_to_genres.csv',
 'sequels.csv',
 'crews.p',
 'WorldBank_POP.csv',
 '.ipynb_checkpoints']

In [7]:
df = pd.DataFrame({'Property': ['House 1', 'House 2', 'House 3'],
'Pirce': [0.8,0.4,0.8],
'Space': [0.6,0.3,0.7],
'Location': [0.99,0.2,0.4],
'Aesthetics': [0.5,0.6,0.8]})

In [8]:
df.head()

  Property  Pirce  Space  Location  Aesthetics
0  House 1    0.8    0.6      0.99         0.5
1  House 2    0.4    0.3      0.20         0.6
2  House 3    0.8    0.7      0.40         0.8

In [9]:
columnas = df.columns
print(f'Las columnas de la fataframne son:{columnas}')
print(120*'*')
columnas_a_fusionar = columnas[1:5]
print(f'Las columnas a fusionar son:{columnas_a_fusionar}')

Las columnas de la fataframne son:Index(['Property', 'Pirce', 'Space', 'Location', 'Aesthetics'], dtype='object')
************************************************************************************************************************
Las columnas a fusionar son:Index(['Pirce', 'Space', 'Location', 'Aesthetics'], dtype='object')

In [11]:
df_long = pd.melt(frame = df,id_vars='Property', value_vars = columnas_a_fusionar)

In [12]:
df_long

   Property    variable  value
0   House 1       Pirce   0.80
1   House 2       Pirce   0.40
2   House 3       Pirce   0.80
3   House 1       Space   0.60
4   House 2       Space   0.30
5   House 3       Space   0.70
6   House 1    Location   0.99
7   House 2    Location   0.20
8   House 3    Location   0.40
9   House 1  Aesthetics   0.50
10  House 2  Aesthetics   0.60
11  House 3  Aesthetics   0.80

In [13]:
billboard = pd.read_csv('billboard.csv')

In [14]:
billboard.head()

,artist,track,date.entered,wk1,wk2,wk3,wk4,wk5,wk6,wk7,...,wk67,wk68,wk69,wk70,wk71,wk72,wk73,wk74,wk75,wk76
0,2 Pac,Baby Don't Cry (Keep...,2000-02-26,87,82.0,72.0,77.0,87.0,94.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2Ge+her,The Hardest Part Of ...,2000-09-02,91,87.0,92.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3 Doors Down,Kryptonite,2000-04-08,81,70.0,68.0,67.0,66.0,57.0,54.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3 Doors Down,Loser,2000-10-21,76,76.0,72.0,69.0,67.0,65.0,55.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,504 Boyz,Wobble Wobble,2000-04-15,57,34.0,25.0,17.0,17.0,31.0,36.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
columns_bill = billboard.columns

In [16]:
columns_bill

Index(['artist', 'track', 'date.entered', 'wk1', 'wk2', 'wk3', 'wk4', 'wk5',
       'wk6', 'wk7', 'wk8', 'wk9', 'wk10', 'wk11', 'wk12', 'wk13', 'wk14',
       'wk15', 'wk16', 'wk17', 'wk18', 'wk19', 'wk20', 'wk21', 'wk22', 'wk23',
       'wk24', 'wk25', 'wk26', 'wk27', 'wk28', 'wk29', 'wk30', 'wk31', 'wk32',
       'wk33', 'wk34', 'wk35', 'wk36', 'wk37', 'wk38', 'wk39', 'wk40', 'wk41',
       'wk42', 'wk43', 'wk44', 'wk45', 'wk46', 'wk47', 'wk48', 'wk49', 'wk50',
       'wk51', 'wk52', 'wk53', 'wk54', 'wk55', 'wk56', 'wk57', 'wk58', 'wk59',
       'wk60', 'wk61', 'wk62', 'wk63', 'wk64', 'wk65', 'wk66', 'wk67', 'wk68',
       'wk69', 'wk70', 'wk71', 'wk72', 'wk73', 'wk74', 'wk75', 'wk76'],
      dtype='object')

In [22]:
billboard_long = pd.melt(
    billboard,
    id_vars=['artist', 'track', 'date.entered'],
    var_name='week',
    value_name='rank'
)

billboard_long.tail()

                 artist                    track date.entered  week  rank
24087       Yankee Grey     Another Nine Minutes   2000-04-29  wk76   NaN
24088  Yearwood, Trisha          Real Live Woman   2000-04-01  wk76   NaN
24089   Ying Yang Twins  Whistle While You Tw...   2000-03-18  wk76   NaN
24090     Zombie Nation            Kernkraft 400   2000-09-02  wk76   NaN
24091   matchbox twenty                     Bent   2000-04-29  wk76   NaN

In [23]:
billboard_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24092 entries, 0 to 24091
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   artist        24092 non-null  object
 1   track         24092 non-null  object
 2   date.entered  24092 non-null  object
 3   week          24092 non-null  object
 4   rank          5307 non-null   float64
dtypes: float64(1), object(4)
memory usage: 941.2+ KB

In [24]:
billboard_long.describe()

              rank
count  5307.000000
mean     51.052384
std      28.966198
min       1.000000
25%      26.000000
50%      51.000000
75%      76.000000
max     100.000000

In [25]:
billboard_long['date.entered']= pd.to_datetime(billboard_long['date.entered'])

In [26]:
billboard_long['year']= billboard_long['date.entered'].dt.year
billboard_long['month']= billboard_long['date.entered'].dt.month
billboard_long['week']= billboard_long['date.entered'].dt.isocalendar().week

In [28]:
billboard_long.dropna(subset=['rank'], inplace=True)

In [30]:
billboard_long = (
    billboard
    .melt(
        id_vars=['artist', 'track', 'date.entered'],
        var_name='variable',
        value_name='rank'
    )
    .assign(
        week=lambda df: df['variable'].str.extract(r'(\d+)', expand=False).astype(int)
    )
    .drop(columns='variable')
    .dropna(subset=['rank'])
)

##Tarea

##SEGUNDA CLASE: LIMPIEZA DE DATOS

In [32]:
datos_crudos= pd.read_csv('datos_crudos.csv')

In [33]:
datos_crudos.head()

,Unnamed: 0,id_paciente,nombre,edad,sexo,diagnostico,peso_kg,fecha_ingreso,fecha_alta,costo_usd,n_medicamentos
0,0,1,Juan García,25.0,M,F412,70.0,2023-01-15,2023-01-20,"$1,200",3.0
1,1,2,maría lopez,34.0,F,F322,58.0,15/02/2023,2023-02-10,$850.50,2.0
2,2,3,PEDRO MARTINEZ,-5.0,m,F321,82.0,2023-03-20,2023-03-15,1500,1.0
3,3,4,Ana Ruiz,128.0,f,F319,91.0,20-04-2023,2023-04-25,"$2,300",4.0
4,4,5,carlos GOMEZ,45.0,Masculino,f209,NaN,2023/05/10,2023-05-08,900,NaN

In [34]:
df = datos_crudos.copy()

In [35]:
df.head(6)

,Unnamed: 0,id_paciente,nombre,edad,sexo,diagnostico,peso_kg,fecha_ingreso,fecha_alta,costo_usd,n_medicamentos
0,0,1,Juan García,25.0,M,F412,70.0,2023-01-15,2023-01-20,"$1,200",3.0
1,1,2,maría lopez,34.0,F,F322,58.0,15/02/2023,2023-02-10,$850.50,2.0
2,2,3,PEDRO MARTINEZ,-5.0,m,F321,82.0,2023-03-20,2023-03-15,1500,1.0
3,3,4,Ana Ruiz,128.0,f,F319,91.0,20-04-2023,2023-04-25,"$2,300",4.0
4,4,5,carlos GOMEZ,45.0,Masculino,f209,NaN,2023/05/10,2023-05-08,900,NaN
5,5,6,Laura Torres,23.0,Femenino,F312,63.0,2023-06-01,2023-06-10,"$1,100",2.0

In [36]:
print(df.shape)
print(110*'»')
print(df.dtypes)
print(110*'»')
print(df.isnull().sum())
print(110*'»')
print(df.duplicated().sum())
print(110*'»')
df.head()

(30, 11)
»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»
Unnamed: 0          int64
id_paciente         int64
nombre             object
edad              float64
sexo               object
diagnostico        object
peso_kg           float64
fecha_ingreso      object
fecha_alta         object
costo_usd          object
n_medicamentos    float64
dtype: object
»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»
Unnamed: 0        0
id_paciente       0
nombre            0
edad              1
sexo              0
diagnostico       0
peso_kg           2
fecha_ingreso     0
fecha_alta        0
costo_usd         0
n_medicamentos    1
dtype: int64
»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»
0
»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»

,Unnamed: 0,id_paciente,nombre,edad,sexo,diagnostico,peso_kg,fecha_ingreso,fecha_alta,costo_usd,n_medicamentos
0,0,1,Juan García,25.0,M,F412,70.0,2023-01-15,2023-01-20,"$1,200",3.0
1,1,2,maría lopez,34.0,F,F322,58.0,15/02/2023,2023-02-10,$850.50,2.0
2,2,3,PEDRO MARTINEZ,-5.0,m,F321,82.0,2023-03-20,2023-03-15,1500,1.0
3,3,4,Ana Ruiz,128.0,f,F319,91.0,20-04-2023,2023-04-25,"$2,300",4.0
4,4,5,carlos GOMEZ,45.0,Masculino,f209,NaN,2023/05/10,2023-05-08,900,NaN

In [37]:
#Eliminacion de duplicados
print(f'Filas antes: {df.shape[0]}')
df = df.drop_duplicates()
print(f'Filas despues: {df.shape[0]}')

Filas antes: 30
Filas despues: 30

In [38]:
datos_crudos.columns

Index(['Unnamed: 0', 'id_paciente', 'nombre', 'edad', 'sexo', 'diagnostico',
       'peso_kg', 'fecha_ingreso', 'fecha_alta', 'costo_usd',
       'n_medicamentos'],
      dtype='object')

In [39]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.encode("ascii", errors="ignores")
    .str.decode("ascii")
)
print(df.columns.tolist())

['unnamed:_0', 'id_paciente', 'nombre', 'edad', 'sexo', 'diagnostico', 'peso_kg', 'fecha_ingreso', 'fecha_alta', 'costo_usd', 'n_medicamentos']

In [40]:
df.head()

,unnamed:_0,id_paciente,nombre,edad,sexo,diagnostico,peso_kg,fecha_ingreso,fecha_alta,costo_usd,n_medicamentos
0,0,1,Juan García,25.0,M,F412,70.0,2023-01-15,2023-01-20,"$1,200",3.0
1,1,2,maría lopez,34.0,F,F322,58.0,15/02/2023,2023-02-10,$850.50,2.0
2,2,3,PEDRO MARTINEZ,-5.0,m,F321,82.0,2023-03-20,2023-03-15,1500,1.0
3,3,4,Ana Ruiz,128.0,f,F319,91.0,20-04-2023,2023-04-25,"$2,300",4.0
4,4,5,carlos GOMEZ,45.0,Masculino,f209,NaN,2023/05/10,2023-05-08,900,NaN

In [41]:
var1='EDaD'

In [42]:
var1.strip().title()

'Edad'

In [43]:
df.head()

,unnamed:_0,id_paciente,nombre,edad,sexo,diagnostico,peso_kg,fecha_ingreso,fecha_alta,costo_usd,n_medicamentos
0,0,1,Juan García,25.0,M,F412,70.0,2023-01-15,2023-01-20,"$1,200",3.0
1,1,2,maría lopez,34.0,F,F322,58.0,15/02/2023,2023-02-10,$850.50,2.0
2,2,3,PEDRO MARTINEZ,-5.0,m,F321,82.0,2023-03-20,2023-03-15,1500,1.0
3,3,4,Ana Ruiz,128.0,f,F319,91.0,20-04-2023,2023-04-25,"$2,300",4.0
4,4,5,carlos GOMEZ,45.0,Masculino,f209,NaN,2023/05/10,2023-05-08,900,NaN

In [44]:
#peso_kg: reemplazar "N/A" string antes de convertir
df['peso_kg'] = df['peso_kg'].replace('N/A', np.nan)
df['peso_kg'] = pd.to_numeric(df['peso_kg'], errors='coerce')
#costo_usd: eeliminar $ y comas
df['costo_usd'] = (
  df['costo_usd']
  .str.replace('$', '', regex=False)
  .str.replace(',', '', regex=False)
  .str.strip()
)
df['costo_usd'] = pd.to_numeric(df['costo_usd'], errors='coerce')
print(df[['peso_kg', 'costo_usd']].dtypes)

peso_kg      float64
costo_usd    float64
dtype: object

In [46]:
df["fecha_ingreso"] = pd.to_datetime(df["fecha_ingreso"], dayfirst=False, infer_datetime_format=True, errors='coerce')
df["fecha_alta"] = pd.to_datetime(df["fecha_alta"], dayfirst=False, infer_datetime_format=True, errors='coerce')

# Verificar cuántas fechas no se pudieron parsear
print(df["fecha_ingreso"].isnull().sum())
print(df["fecha_alta"].isnull().sum())

4
0

/tmp/ipykernel_4448/2871156743.py:1: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df["fecha_ingreso"] = pd.to_datetime(df["fecha_ingreso"], dayfirst=False, infer_datetime_format=True, errors='coerce')
/tmp/ipykernel_4448/2871156743.py:2: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df["fecha_alta"] = pd.to_datetime(df["fecha_alta"], dayfirst=False, infer_datetime_format=True, errors='coerce')

In [47]:
# Edad: rango biológicamente plausible
mask_edad = (df["edad"] < 0) | (df["edad"] > 120)
print(f"Edades fuera de rango: {mask_edad.sum()}")
df.loc[mask_edad, "edad"] = np.nan
# Peso: rango plausible para humanos adultos
mask_peso = (df["peso_kg"] < 2) | (df["peso_kg"] > 300)
df.loc[mask_peso, "peso_kg"] = np.nan

Edades fuera de rango: 2

In [48]:
# Alta no puede ser anterior al ingreso
mask_fechas = df["fecha_alta"] < df["fecha_ingreso"]
print(f"Inconsistencias fecha ingreso/alta: {mask_fechas.sum()}")
df.loc[mask_fechas, "fecha_alta"] = np.nan

Inconsistencias fecha ingreso/alta: 1

In [49]:
print(df.isnull().sum())
# Edad y peso: imputar con mediana (robusta a atípicos)
df["edad"] = df["edad"].fillna(df["edad"].median())
df["peso_kg"] = df["peso_kg"].fillna(df["peso_kg"].median())
# n_medicamentos: imputar con moda
moda_med = df["n_medicamentos"].mode()[0]
df["n_medicamentos"] = df["n_medicamentos"].fillna(moda_med)
# sexo: dejar como NaN si no es recuperable
# fecha_alta: dejar como NaN, es un dato clínico no imputable
print(df.isnull().sum())

unnamed:_0        0
id_paciente       0
nombre            0
edad              3
sexo              0
diagnostico       0
peso_kg           2
fecha_ingreso     4
fecha_alta        1
costo_usd         0
n_medicamentos    1
dtype: int64
unnamed:_0        0
id_paciente       0
nombre            0
edad              0
sexo              0
diagnostico       0
peso_kg           0
fecha_ingreso     4
fecha_alta        1
costo_usd         0
n_medicamentos    0
dtype: int64

In [50]:
df["sexo"] = df["sexo"].astype("category")
df["diagnostico"] = df["diagnostico"].astype("category")
df["n_medicamentos"] = df["n_medicamentos"].astype(int)
df["id_paciente"] = df["id_paciente"].astype(int)
print(df.dtypes)

unnamed:_0                 int64
id_paciente                int64
nombre                    object
edad                     float64
sexo                    category
diagnostico             category
peso_kg                  float64
fecha_ingreso     datetime64[ns]
fecha_alta        datetime64[ns]
costo_usd                float64
n_medicamentos             int64
dtype: object

In [51]:
def resumen_final(df):
  print("=== FORMA ===")
  print(df.shape)
  print("\n=== FALTANTES RESTANTES ===")
  print(df.isnull().sum())
  print("\n=== TIPOS ===")
  print(df.dtypes)
  print("\n=== MUESTRA ===")
  print(df.head())
resumen_final(df)

=== FORMA ===
(30, 11)

=== FALTANTES RESTANTES ===
unnamed:_0        0
id_paciente       0
nombre            0
edad              0
sexo              0
diagnostico       0
peso_kg           0
fecha_ingreso     4
fecha_alta        1
costo_usd         0
n_medicamentos    0
dtype: int64

=== TIPOS ===
unnamed:_0                 int64
id_paciente                int64
nombre                    object
edad                     float64
sexo                    category
diagnostico             category
peso_kg                  float64
fecha_ingreso     datetime64[ns]
fecha_alta        datetime64[ns]
costo_usd                float64
n_medicamentos             int64
dtype: object

=== MUESTRA ===
   unnamed:_0  id_paciente          nombre  edad       sexo diagnostico  \
0           0            1     Juan García  25.0          M        F412
1           1            2     maría lopez  34.0          F        F322
2           2            3  PEDRO MARTINEZ  39.0          m       F321
3           3            4        Ana Ruiz  39.0          f        F319
4           4            5    carlos GOMEZ  45.0  Masculino        f209

   peso_kg fecha_ingreso fecha_alta  costo_usd  n_medicamentos
0     70.0    2023-01-15 2023-01-20     1200.0               3
1     58.0           NaT 2023-02-10      850.5               2
2     82.0    2023-03-20        NaT     1500.0               1
3     91.0           NaT 2023-04-25     2300.0               4
4     70.5           NaT 2023-05-08      900.0               2

In [52]:
# Diccionario de listas: destino -> [variantes]
mapa_sexo_listas = {
  "M": ["m", "masculino", "male", "hombre"],
  "F": ["f", "femenino", "female", "mujer"],
  np.nan: ["999", "ns/nr", "desconocido", ""]
}
# Invertir: cada variante apunta a su destino
mapa_invertido = {
  variante: destino
  for destino, variantes in mapa_sexo_listas.items()
  for variante in variantes
}

In [53]:
mapa_invertido

{'m': 'M',
 'masculino': 'M',
 'male': 'M',
 'hombre': 'M',
 'f': 'F',
 'femenino': 'F',
 'female': 'F',
 'mujer': 'F',
 '999': nan,
 'ns/nr': nan,
 'desconocido': nan,
 '': nan}

In [54]:
print(mapa_invertido)
# {'m': 'M', 'masculino': 'M', ..., 'f': 'F', ..., '999': nan}
# Aplicar igual que antes
df["sexo"] = df["sexo"].str.strip().str.lower().map(mapa_invertido)

{'m': 'M', 'masculino': 'M', 'male': 'M', 'hombre': 'M', 'f': 'F', 'femenino': 'F', 'female': 'F', 'mujer': 'F', '999': nan, 'ns/nr': nan, 'desconocido': nan, '': nan}

In [55]:
df_tarea = pd.read_csv('datos_crudos_tarea.csv')

In [56]:
df_tarea.head()

,Unnamed: 0,id_paciente,fecha_consulta,edad,sexo,peso_kg,altura_m,presion_arterial,glucosa_mg_dL,colesterol_total,fuma,actividad_fisica,imc_calculado
0,0,524,2022-01-23 00:00:00,73,MUJER,80.6,2.38,89/97,NaN,-100,0,alta,NaN
1,1,603,2023-03-02 00:00:00,7,X,126.3,1.18,88/79,95,-100,0,Sedentario,NaN
2,2,527,2022-04-28 00:00:00,68,F,37.7,20,118/51,500,-100,no,Sedentario,NaN
3,3,32,2022-05-06 00:00:00,96,f,47.5,0.45,195/105,300,bueno,SI,Sedentario,NaN
4,4,617,2023-06-07 00:00:00,72,Mujer,198.8,0.81,126/87,85,120,0,Baja,NaN

In [57]:
import pandas as pd # importo pandas para manejar los datos
import numpy as np # importo numpy por si necesito operaciones numéricas
df = pd.read_csv('datos_crudos_tarea.csv') # cargo el archivo de datos crudos
print(df.head()) # miro las primeras filas para entender cómo vienen los datos
print(df.info()) # reviso tipos de datos y si hay valores nulos
print(df.columns) # veo los nombres de las columnas
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
# limpio los nombres de las columnas (quito espacios, paso a minúscula y reemplazo
print(df.isnull().sum()) # cuento cuántos valores nulos hay por columna
df = df.dropna(how='all')
# elimino filas que están completamente vacías (todos los valores en NaN)
columnas = df.columns # guardo todas las columnas en una variable
id_vars = columnas[:3]
# tomo las primeras columnas como identificadores
value_vars = columnas[3:]
# tomo el resto de columnas como variables que quiero reorganizar
df_limpio = pd.melt(df, id_vars=id_vars, value_vars=value_vars)
# transformo el dataset de formato ancho a formato largo
df_limpio.columns = list(id_vars) + ['variable', 'valor']
# renombro las columnas para que queden más claras
df_limpio = df_limpio.dropna(subset=['valor'])
# elimino las filas donde el valor es nulo porque no sirven para el análisis
df_limpio['valor'] = pd.to_numeric(df_limpio['valor'], errors='coerce')
# convierto la columna valor a numérica por si viene como texto
print(df_limpio.head()) # reviso cómo quedó el dataset limpio
print(df_limpio.info()) # verifico nuevamente la estructura
print(df_limpio.describe()) # miro estadísticas básicas para validar los datos
df_limpio.to_csv('datos_limpios.csv', index=False)
# guardo el dataset limpio en un nuevo archivo

   Unnamed: 0  id_paciente       fecha_consulta edad   sexo peso_kg altura_m  \
0           0          524  2022-01-23 00:00:00   73  MUJER    80.6     2.38
1           1          603  2023-03-02 00:00:00    7      X   126.3     1.18
2           2          527  2022-04-28 00:00:00   68      F    37.7       20
3           3           32  2022-05-06 00:00:00   96      f    47.5     0.45
4           4          617  2023-06-07 00:00:00   72  Mujer   198.8     0.81

  presion_arterial glucosa_mg_dL colesterol_total fuma actividad_fisica  \
0            89/97           NaN             -100    0             alta
1            88/79            95             -100    0       Sedentario
2           118/51           500             -100   no       Sedentario
3          195/105           300            bueno   SI       Sedentario
4           126/87            85              120    0             Baja

   imc_calculado
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1020 non-null   int64
 1   id_paciente       1020 non-null   int64
 2   fecha_consulta    1020 non-null   object
 3   edad              1006 non-null   object
 4   sexo              917 non-null    object
 5   peso_kg           1006 non-null   object
 6   altura_m          1006 non-null   object
 7   presion_arterial  1020 non-null   object
 8   glucosa_mg_dL     923 non-null    object
 9   colesterol_total  886 non-null    object
 10  fuma              908 non-null    object
 11  actividad_fisica  929 non-null    object
 12  imc_calculado     0 non-null      float64
dtypes: float64(1), int64(2), object(10)
memory usage: 103.7+ KB
None
Index(['Unnamed: 0', 'id_paciente', 'fecha_consulta', 'edad', 'sexo',
       'peso_kg', 'altura_m', 'presion_arterial', 'glucosa_mg_dL',
       'colesterol_total', 'fuma', 'actividad_fisica', 'imc_calculado'],
      dtype='object')
unnamed:_0             0
id_paciente            0
fecha_consulta         0
edad                  14
sexo                 103
peso_kg               14
altura_m              14
presion_arterial       0
glucosa_mg_dl         97
colesterol_total     134
fuma                 112
actividad_fisica      91
imc_calculado       1020
dtype: int64
   unnamed:_0  id_paciente       fecha_consulta variable  valor
0           0          524  2022-01-23 00:00:00     edad   73.0
1           1          603  2023-03-02 00:00:00     edad    7.0
2           2          527  2022-04-28 00:00:00     edad   68.0
3           3           32  2022-05-06 00:00:00     edad   96.0
4           4          617  2023-06-07 00:00:00     edad   72.0
<class 'pandas.core.frame.DataFrame'>
Index: 8601 entries, 0 to 9179
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   unnamed:_0      8601 non-null   int64
 1   id_paciente     8601 non-null   int64
 2   fecha_consulta  8601 non-null   object
 3   variable        8601 non-null   object
 4   valor           4718 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 403.2+ KB
None
        unnamed:_0  id_paciente        valor
count  8601.000000  8601.000000  4718.000000
mean    510.835949   503.005464   152.368964
std     294.762564   288.956400   734.390120
min       0.000000     1.000000  -100.000000
25%     256.000000   253.000000     1.210000
50%     512.000000   505.000000    45.000000
75%     766.000000   754.000000   120.000000
max    1019.000000  1000.000000  9999.000000